apiVersion: v1
kind: Secret
metadata:
  name: cattle-credentials-87c77f0
  namespace: cattle-system
type: Opaque
data:
  url: "aHR0cHM6Ly8xNjUuMjIuNjIuMTY1"
  token: "czduNGcyNHQ4ajltNHptbnpjbXJ2c2NkOG5kc3B4Zjg1dDg5ZndkZ3F4cmQ1ZHAyZzJ4Nnhy"
  namespace: ""