# -*- mode: ruby -*-
# vi: set ft=ruby :

# Tạo máy ảo từ box centos/7, gán địa chỉ IP, đặt hostname, gán 2GB bộ nhớ, 2 cpus  
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "public_network", bridge: "VirtualBox Host-Only Ethernet Adapter"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.hostname = "k8s-master-02"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "k8s-master-02"
       vb.cpus = 2
       vb.memory = "4096"
    end
    
    # Chạy file install-docker-kube.sh sau khi nạp Box
    config.vm.provision "shell", path: "./../install-containerd-kube.sh"
  
    # Chạy các lệnh shell
    config.vm.provision "shell", inline: <<-SHELL
      # Đặt pass 123 có tài khoản root và cho phép SSH
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  # Ghi nội dung sau ra file /etc/hosts để truy cập được các máy theo HOSTNAME
  cat >>/etc/hosts<<EOF
  192.168.56.7 elb
  192.168.56.8 haproxy-01
  192.168.56.9 haproxy-02
  192.168.56.10 k8s-master-01
  192.168.56.11 k8s-master-02
  192.168.56.12 k8s-master-03
  192.168.56.13 k8s-worker-01
  192.168.56.14 k8s-worker-02
  192.168.56.15 k8s-worker-03
  192.168.56.16 rancher
  192.168.56.17 devci
  192.168.56.18 gitlab
  192.168.56.19 harbor

  EOF
    SHELL
  end