kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadbslave-pvc
spec:
  storageClassName: mariadbslave-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi